// <auto-generated />

using System;
using CO2Monitor.Infrastructure.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CO2Monitor.Infrastructure.Migrations.LogRecordsDb {
	[DbContext(typeof(LogRecordsDbContext))]
	class LogRecordsDbContextModelSnapshot : ModelSnapshot {
		protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

			modelBuilder.Entity("CO2Monitor.Core.Entities.LogRecord", b => {
				b.Property<int?>("Id").ValueGeneratedOnAdd();

				b.Property<int?>("EventId");

				b.Property<string>("LogLevel");

				b.Property<string>("Message");

				b.Property<DateTime>("Time");

				b.HasKey("Id");

				b.HasIndex("Time");

				b.ToTable("Records");
			});
#pragma warning restore 612, 618
		}
	}
}
