// <auto-generated />
using System;
using CO2Monitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CO2Monitor.Infrastructure.Migrations
{
    [DbContext(typeof(StateMeasurementDbContext))]
    [Migration("20190716145916_StateMeasurementInitialCreate")]
    partial class StateMeasurementInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("CO2Monitor.Core.Entities.DeviceStateMeasurement", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DeviceId");

                    b.Property<string>("State");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Time");

                    b.HasIndex("DeviceId", "Time");

                    b.ToTable("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
