// <auto-generated />

using System;
using CO2Monitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CO2Monitor.Infrastructure.Migrations {
	[DbContext(typeof(StateMeasurementDbContext))]
	class StateMeasurementDbContextModelSnapshot : ModelSnapshot {
		protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

			modelBuilder.Entity("CO2Monitor.Core.Entities.DeviceStateMeasurement", b => {
				b.Property<int?>("Id").ValueGeneratedOnAdd();

				b.Property<int>("DeviceId");

				b.Property<string>("State");

				b.Property<DateTime>("Time");

				b.HasKey("Id");

				b.HasIndex("DeviceId");

				b.HasIndex("Time");

				b.HasIndex("DeviceId", "Time");

				b.ToTable("Measurements");
			});
#pragma warning restore 612, 618
		}
	}
}
